### ISSUE TITLE
School Accreditation Cloudfiles Editing

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-emis-education-survey-tool#20]
Edit a surveyTag (which is used for merging) [Probably Omega-R at the tablet level]. Need to carefully assess this at the tablet level to make sure there are not any repercussion to this added "feature"

**Comment by marinaomega** [comment]
Ghislain, could you please give some more details on that? Not so clear for now. Thanks!

**Comment by ghachey** [comment]
The date shown below is set at the time of survey creation. It can not be changed after.

![surveyTag](https://user-images.githubusercontent.com/1091769/142096068-e88aedeb-0596-4a54-b750-ed52d6505b19.png)

The problem with this is that when users forget to create the survey with the same date they are not able to merge their worker tablet with the team leader tablet.

Ideally, we could edit this date after the survey has has already started.

**Comment by marinaomega** [comment]
Hi @ghachey It is possible to add functionality to change the date, but this can lead to duplicating the survey in the cloud, since the date (surveyTag) is part of the survey name, but after setting a new date, surveys can be merged. There will be two polls, the old version with the old date and the new version with the new date and latest changes, provided that the old version was uploaded to the cloud, if not, then there will be no duplication, since the file name is generated when we send it to the cloud. Is it ok this way?

**Comment by ghachey** [comment]
Hi @marinaomega If the only downside is that we will have a duplicate of the survey (if already synced to cloud) then yes, this is desirable. The duplicate can be located from within the EMIS web app and cleaned up after in those cases. Please proceed with this change and do thorough testing to make sure this will be the only downside.

**Comment by ghachey** [comment]
I can confirm this is working on my latest tested app versions.
